### ISSUE TITLE
部分函数未实现

### ISSUE THREAD

**Issue by 1623040547** [luojilab/DataTransHub#11]
/src/core/base/file.h中，类File中的部分函数在file.cpp中没有进行实现，且这些函数有被引用。

![1f0c981c-8d65-49c3-8fff-99956ee95f6e](https://github.com/user-attachments/assets/09367a54-66b1-4b95-9b90-bacacdbab624)

**Comment by lixiaoyu0123** [comment]
> /src/core/base/file.h中，类File中的部分函数在file.cpp中没有进行实现，且这些函数有被引用。
> 
> ![1f0c981c-8d65-49c3-8fff-99956ee95f6e](https://private-user-images.githubusercontent.com/72777780/374771197-09367a54-66b1-4b95-9b90-bacacdbab624.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDUxNzQsIm5iZiI6MTcyODQ0NDg3NCwicGF0aCI6Ii83Mjc3Nzc4MC8zNzQ3NzExOTctMDkzNjdhNTQtNjZiMS00Yjk1LTliOTAtYmFjYWNkYmFiNjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAzMzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZmU0ODEzMjYwOTkyZGU4NWMzY2YzMmE0ZjU5MWI4NDY0N2ExYWJjMWI3ZGI0NjY1MGUwMzAwZDlhMjM5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wDVwEthfyRCsAW0zbb07uFMqAFZBUI_F5TG5KvcFzIo)

这部分函数的实现在platform中的file中，这些与平台的特性相关，所以实现会分不同的平台。

**Comment by 1623040547** [comment]
> > /src/core/base/file.h中，类File中的部分函数在file.cpp中没有进行实现，且这些函数有被引用。
> > ![1f0c981c-8d65-49c3-8fff-99956ee95f6e](https://private-user-images.githubusercontent.com/72777780/374771197-09367a54-66b1-4b95-9b90-bacacdbab624.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDUxNzQsIm5iZiI6MTcyODQ0NDg3NCwicGF0aCI6Ii83Mjc3Nzc4MC8zNzQ3NzExOTctMDkzNjdhNTQtNjZiMS00Yjk1LTliOTAtYmFjYWNkYmFiNjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDAzMzQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZmU0ODEzMjYwOTkyZGU4NWMzY2YzMmE0ZjU5MWI4NDY0N2ExYWJjMWI3ZGI0NjY1MGUwMzAwZDlhMjM5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wDVwEthfyRCsAW0zbb07uFMqAFZBUI_F5TG5KvcFzIo)
> 
> 这部分函数的实现在platform中的file中，这些与平台的特性相关，所以实现会分不同的平台。

是的，这部分是我漏掉了
