### ISSUE TITLE
不同实例打印日志没有完全隔离

### ISSUE THREAD

**Issue by kkk154** [luojilab/DataTransHub#2]
创建了三个flog实例，在分别三个线程中打日志，日志文件的内容没有按实例名隔离。

**Comment by lixiaoyu0123** [comment]
麻烦问下3个flog实例的创建是通过    public synchronized static Flog makeFlog(String cacheDir, String dataDir, String encryptKey) 方法创建的吗？
另外，cacheDir 和 dataDir 路径 不同的实例需要配置不同的路径。否则会导致多个实例数据打入相同文件。

**Comment by kkk154** [comment]
> 麻烦问下3个flog实例的创建是通过 public synchronized static Flog makeFlog(String cacheDir, String dataDir, String encryptKey) 方法创建的吗？
> 另外，cacheDir 和 dataDir 路径 不同的实例需要配置不同的路径。否则会导致多个实例数据打入相同文件。



> 麻烦问下3个flog实例的创建是通过 public synchronized static Flog makeFlog(String cacheDir, String dataDir, String encryptKey) 方法创建的吗？
> 另外，cacheDir 和 dataDir 路径 不同的实例需要配置不同的路径。否则会导致多个实例数据打入相同文件。

是通过makeFlog创建的，相同的目录，设置了不同的前缀，应该是获取文件列表的接口没有区分前缀导致的

**Comment by lixiaoyu0123** [comment]
好的，明白了，不同实例的log的存储目录 建议是分开的，目前是通过目录来区分不同实例的log文件存储。建议是使用上目录最好分割，不用前缀筛选，否则如果实例过多，会对筛选造成一定的相互影响。
