### ISSUE TITLE
换行符问题

### ISSUE THREAD

**Issue by zhangyuChen1991** [luojilab/DataTransHub#8]
Android这边调用之后发现写到文件的日志换行符都被处理掉了，这个有办法可以解决吗

**Comment by zhangyuChen1991** [comment]
好像是因为各个操作系统换行符不一样的原因，Android是\n，windows是\r\n，所以在代码里输出的带\n的日志，解密后在windows上打开看不到换行符。
但是之前直接用xlog的时候是没有这个问题的

**Comment by shaobin0604** [comment]
@zhangyuChen1991 绝大部分 windows 上的文本编辑器都可以设置换行符
